import { createSlice } from "@reduxjs/toolkit";

const menus = [
  {
    id: 1,
    parent_id: 0,
    path: "/dashboard/console",
    name: "首页",
    icon: "icon-home",
    component: "Dashboard/Console",
  },
  {
    id: 2,
    parent_id: 0,
    path: "/dashboard/analysis",
    name: "数据分析",
    icon: "icon-hangyebaogao",
    component: "Dashboard/Analysis",
  },
  {
    id: 3,
    parent_id: 0,
    path: "/merchant",
    name: "商户管理",
    icon: null,
    component: null,
  },
  {
    id: 4,
    parent_id: 3,
    path: "/merchant/user",
    name: "用户管理",
    icon: "icon-yonghu",
    component: "Merchant/User",
  },
  {
    id: 5,
    parent_id: 3,
    path: "/merchant/group",
    name: "用户组管理",
    icon: "icon-customer-filter",
    component: "Merchant/Group",
  },
  {
    id: 6,
    parent_id: 3,
    path: "/merchant/permission",
    name: "权限管理",
    icon: "icon-unlock",
    component: "Merchant/Permission",
  },
  {
    id: 7,
    parent_id: 3,
    path: "/merchant/application",
    name: "应用管理",
    icon: "icon-all",
    component: "Merchant/Application",
  },
  {
    id: 8,
    parent_id: 3,
    path: "/merchant/withdraw",
    name: "提现管理",
    icon: "icon-stop",
    component: "Merchant/Withdraw",
  },
  {
    id: 9,
    parent_id: 3,
    path: "/merchant/bill",
    name: "账单管理",
    icon: "icon-business-icon-feeds",
    component: "Merchant/Bill",
  },
  {
    id: 10,
    parent_id: 3,
    path: "/merchant/message",
    name: "站内信管理",
    icon: "icon-all",
    component: "Merchant/Message",
  },
  {
    id: 11,
    parent_id: 3,
    path: "/merchant/identity",
    name: "身份证管理",
    icon: "icon-zhengshuyanzhen",
    component: "Merchant/Identity",
  },
  {
    id: 12,
    parent_id: 3,
    path: "/merchant/card",
    name: "银行卡管理",
    icon: "icon-money-credit-card",
    component: "Merchant/Card",
  },
  {
    id: 13,
    parent_id: 0,
    path: "/fund",
    name: "支付管理",
    icon: null,
    component: null,
  },
  {
    id: 14,
    parent_id: 13,
    path: "/fund/payment/bank",
    name: "银行管理",
    icon: "icon-money-bank",
    component: "Fund/Bank",
  },
  {
    id: 15,
    parent_id: 13,
    path: "/fund/payment/channel",
    name: "通道管理",
    icon: "icon-haiwaitequan",
    component: "Fund/Payment",
  },
  {
    id: 16,
    parent_id: 13,
    path: "/fund/order",
    name: "订单管理",
    icon: "icon-shopping",
    component: "Fund/Order",
  },
  {
    id: 17,
    parent_id: 13,
    path: "/fund/complaint",
    name: "消费者投诉管理",
    icon: "icon-trade-alert",
    component: "Fund/Complaint",
  },
  {
    id: 18,
    parent_id: 0,
    path: "/system",
    name: "系统管理",
    icon: null,
    component: null,
  },
  {
    id: 19,
    parent_id: 18,
    path: "/system/user",
    name: "用户管理",
    icon: "icon-customer-group",
    component: "System/User",
  },
  {
    id: 20,
    parent_id: 18,
    path: "/system/role",
    name: "角色管理",
    icon: "icon-customer-filter",
    component: "System/Role",
  },
  {
    id: 21,
    parent_id: 18,
    path: "/system/permission",
    name: "权限管理",
    icon: "icon-unlock",
    component: "System/Permission",
  },
  {
    id: 22,
    parent_id: 18,
    path: "/system/department",
    name: "机构管理",
    icon: "icon-shiligongchang",
    component: "System/Department",
  },
  {
    id: 23,
    parent_id: 18,
    path: "/system/dictionary",
    name: "字典管理",
    icon: "icon-teaching",
    component: "System/Dictionary",
  },
  {
    id: 24,
    parent_id: 18,
    path: "/system/configuration",
    name: "配置管理",
    icon: "icon-settings",
    component: "System/Configuration",
  },
  {
    id: 25,
    parent_id: 18,
    path: "/system/log",
    name: "日志管理",
    icon: "icon-settings",
    component: "System/Log",
  },
];

const initialState: any = {
  userInfo: {
    id: 1,
    email: "admin@nanoa.cn",
    nickname: "超级管理员",
    menus: menus,
  },
};

const userSlice = createSlice({
  name: "user",
  initialState,
  reducers: {},
});

export default userSlice.reducer;
