import { createSlice } from "@reduxjs/toolkit";

const menus = [
  {
    id: 1,
    parent_id: 0,
    path: "/dashboard/console",
    name: "首页",
    icon: "icon-home",
    component: "Dashboard/Console",
  },
  {
    id: 2,
    parent_id: 0,
    path: "/dashboard/analysis",
    name: "数据分析",
    icon: "icon-hangyebaogao",
    component: "Dashboard/Analysis",
  },
  {
    id: 3,
    parent_id: 0,
    path: "/member",
    name: "会员管理",
    icon: null,
    component: null,
  },
  {
    id: 4,
    parent_id: 3,
    path: "/member/user",
    name: "用户管理",
    icon: "icon-yonghu",
    component: "Member/User",
  },
  {
    id: 5,
    parent_id: 3,
    path: "/member/group",
    name: "用户组管理",
    icon: "icon-customer-filter",
    component: "Member/Group",
  },
  {
    id: 6,
    parent_id: 3,
    path: "/member/withdraw",
    name: "提现管理",
    icon: "icon-stop",
    component: "Member/Withdraw",
  },
  {
    id: 7,
    parent_id: 3,
    path: "/member/bill",
    name: "账单管理",
    icon: "icon-business-icon-feeds",
    component: "Member/Bill",
  },
  {
    id: 8,
    parent_id: 3,
    path: "/member/application",
    name: "应用管理",
    icon: "icon-all",
    component: "Member/Application",
  },
  {
    id: 9,
    parent_id: 3,
    path: "/member/identity",
    name: "身份证管理",
    icon: "icon-zhengshuyanzhen",
    component: "Member/Identity",
  },
  {
    id: 10,
    parent_id: 3,
    path: "/member/card",
    name: "银行卡管理",
    icon: "icon-money-credit-card",
    component: "Member/Card",
  },
  {
    id: 11,
    parent_id: 0,
    path: "/fund",
    name: "资金管理",
    icon: null,
    component: null,
  },
  {
    id: 12,
    parent_id: 11,
    path: "/fund/bank",
    name: "银行管理",
    icon: "icon-money-bank",
    component: "Fund/Bank",
  },
  {
    id: 14,
    parent_id: 11,
    path: "/fund/payment",
    name: "支付管理",
    icon: "icon-haiwaitequan",
    component: "Fund/Payment",
  },
  {
    id: 15,
    parent_id: 11,
    path: "/fund/order",
    name: "订单管理",
    icon: "icon-shopping",
    component: "Fund/Order",
  },
  {
    id: 16,
    parent_id: 11,
    path: "/fund/complaint",
    name: "消费者投诉管理",
    icon: "icon-trade-alert",
    component: "Fund/Complaint",
  },
  {
    id: 17,
    parent_id: 0,
    path: "/system",
    name: "系统管理",
    icon: null,
    component: null,
  },
  {
    id: 18,
    parent_id: 17,
    path: "/system/user",
    name: "用户管理",
    icon: "icon-customer-group",
    component: "System/User",
  },
  {
    id: 19,
    parent_id: 17,
    path: "/system/role",
    name: "角色管理",
    icon: "icon-customer-filter",
    component: "System/Role",
  },
  {
    id: 20,
    parent_id: 17,
    path: "/system/permission",
    name: "权限管理",
    icon: "icon-unlock",
    component: "System/Permission",
  },
  {
    id: 21,
    parent_id: 17,
    path: "/system/department",
    name: "部门管理",
    icon: "icon-shiligongchang",
    component: "System/Department",
  },
  {
    id: 22,
    parent_id: 17,
    path: "/system/position",
    name: "岗位管理",
    icon: "icon-zhuanshujingli",
    component: "System/Position",
  },
  {
    id: 23,
    parent_id: 17,
    path: "/system/tenant",
    name: "租户管理",
    icon: "icon-trust",
    component: "System/Tenant",
  },
  {
    id: 24,
    parent_id: 17,
    path: "/system/files",
    name: "文件管理",
    icon: "icon-folder",
    component: "System/Files",
  },
  {
    id: 25,
    parent_id: 17,
    path: "/system/dictionary",
    name: "字典管理",
    icon: "icon-teaching",
    component: "System/Dictionary",
  },
  {
    id: 26,
    parent_id: 17,
    path: "/system/configuration",
    name: "配置管理",
    icon: "icon-settings",
    component: "System/Configuration",
  },
];

const initialState: any = {
  userInfo: {
    id: 1,
    email: "admin@nanoa.cn",
    nickname: "超级管理员",
    menus: menus,
  },
};

const userSlice = createSlice({
  name: "user",
  initialState,
  reducers: {},
});

export default userSlice.reducer;
