import "element-plus/es/components/table-v2/style/index";
import "element-plus/es/components/checkbox/style/index";
import "element-plus/es/components/checkbox-group/style/index";
import "element-plus/es/components/empty/style/index";
import "element-plus/es/components/icon/style/index";
import "element-plus/es/components/scrollbar/style/index";
import "element-plus/es/components/button/style/index";
import "../../ele-tooltip/style/index";
import "./index.scss";
